version: '3.8'
services: 
  frontend:
    build: ./frontend
    ports:
      - 80:3000
    restart: always
    
  user-service-service:
    build: ./user-service
    restart: always 
    depends_on:
      - mongodb
      - backend
    env_file: 
      - ./user-service/.env

  matching-service-service:
    build: ./matching-service
    restart: always
    depends_on:
      - backend 
    env_file:
      - ./matching-service/.env

  question-service-service:
    build: ./question-service
    depends_on:
      - backend 
    restart: always

  collab-service-service:
    build: ./collab-service
    restart: always
    depends_on:
      - backend 
    environment: 
      - ENV=DEV

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ./user-service/data/db/:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=PASSWORD

  backend:
    build: ./gateway
    ports: 
      - 3001:80
    restart: always

