version: '3.8'
services: 
  frontend:
    build: ./frontend
    ports:
      - 80:3000
    restart: always
    
  user-service-service:
    build: ./user-service
    restart: always 
    depends_on:
      - mongodb
      - gateway
    environment: 
      - ENV=DEV
      - DB_LOCAL_URI=mongodb://USERNAME:PASSWORD@mongodb/user-db

  matching-service-service:
    build: ./matching-service
    restart: always
    depends_on:
      - gateway
    environment: 
      - ENV=DEV
      - DB_LOCAL_URI=sqlite::memory

  question-service-service:
    build: ./question-service
    depends_on:
      - gateway
    restart: always

  collab-service-service:
    build: ./collab-service
    restart: always
    depends_on:
      - gateway
    environment: 
      - ENV=DEV

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ./user-service/data/db/:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=PASSWORD

  gateway:
    build: ./gateway
    ports: 
      - 3001:80
    restart: always

