apiVersion: apps/v1
kind: Deployment
metadata:
  name: collab-service-deployment
  labels:
    app: collab-service
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: collab-service
  template:
    metadata:
      labels:
        app: collab-service
    spec:
      containers:
        - name: collab-service-deployment
          image: cs3219g27/collab-service:latest
          ports:
            - name: cs-http
              containerPort: 8003
          resources:
            limits:
              cpu: 60m
              memory: 150Mi
          env: 
            - name: REACT_APP_RAPID_API_URL
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: REACT_APP_RAPID_API_URL
            - name: REACT_APP_RAPID_API_HOST
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: REACT_APP_RAPID_API_HOST
            - name: REACT_APP_RAPID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: REACT_APP_RAPID_API_KEY
