apiVersion: apps/v1
kind: Deployment
metadata:
  name: comm-service-deployment
  labels:
    app: comm-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comm-service
  template:
    metadata:
      labels:
        app: comm-service
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-key
      containers:
        - name: comm-service-deployment
          image: cs3219g27/comm-service:latest
          ports:
            - name: cms-http
              containerPort: 8004
          resources:
            limits:
              cpu: 80m
              memory: 150Mi
          volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: JWT_ACCESS_SECRET
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: comm-service-secret
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: comm-service-secret
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: comm-service-secret
                  key: REDIS_PASSWORD
