apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: cs3219g27
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cs3219g27
  template:
    metadata:
      labels:
        app: cs3219g27
    spec:
      containers:
        - name: frontend-deployment
          image: cs3219g27/frontend:latest
          ports:
            - name: fe-http
              containerPort: 3000
          resources:
            limits:
              cpu: 40m
              memory: 100Mi
          env:
            - name: URI_USER_SVC
              value: http://user-service-service:8000
            - name: URI_MATCHING_SVC
              value: http://matching-service-service:8001
