apiVersion: v1
kind: Service
metadata:
  labels:
    app: matching-service
  name: matching-service-service
spec:
  selector:
    app: matching-service
  type: ClusterIP
  ports:
    - name: ms-http
      port: 8001
      protocol: TCP
      targetPort: ms-http
