apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service-deployment
  labels:
    app: matching-service
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      containers:
        - name: matching-service-deployment
          image: cs3219g27/matching-service:latest
          ports:
            - name: ms-http
              containerPort: 8001
          resources:
            limits:
              cpu: 60m
              memory: 150Mi
          env: 
            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: JWT_ACCESS_SECRET
