apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service-deployment
  labels:
    app: cs3219g27
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cs3219g27
  template:
    metadata:
      labels:
        app: cs3219g27
    spec:
      containers:
        - name: matching-service-deployment
          image: cs3219g27/matching-service:latest
          ports:
            - name: ms-http
              containerPort: 8001
          resources:
            limits:
              cpu: 40m
              memory: 100Mi
