apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-key
      containers:
        - name: user-service-deployment
          image: cs3219g27/user-service:latest
          ports:
            - name: us-http
              containerPort: 8000
          resources:
            limits:
              cpu: 40m
              memory: 300Mi
          volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: ENV
              value: PROD
            - name: DB_CLOUD_URI
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: DB_CLOUD_URI
            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: JWT_ACCESS_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: JWT_REFRESH_SECRET
            - name: CORS_ORIGIN
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: CORS_ORIGIN
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: SENDGRID_API_KEY
            - name: USER_SVC_SENDER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: USER_SVC_SENDER_EMAIL
            - name: FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: FRONTEND_URL
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: REDIS_PASSWORD
