export const STATUS_CODE_LOGIN = 200
export const STATUS_CODE_CREATED = 201
export const STATUS_CODE_MISSING = 400
export const STATUS_CODE_INVALID_PASSWORD = 401
export const STATUS_CODE_INVALID_USERNAME = 404
export const STATUS_CODE_CONFLICT = 409
export const STATUS_DATABASE_FAILURE = 500