version: '3'
services:
  redis-token-store-service:
    command: redis-server --requirepass team27
    image: redis
    ports:
      - 6379:6379
  redis-matching-service:
    command: redis-server --requirepass team27
    image: redis
    ports:
      - 6380:6379
  redis-collab:
    command: redis-server --requirepass team27
    image: redis
    ports:
      - 6381:6379
  redis-comm:
    command: redis-server --requirepass team27
    image: redis
    ports:
      - 6382:6379