name: frontend-cd

on:
  push:
    branches:
      - "main"
    paths:
      - frontend/**
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: kubectl - Google Cloud GKE cluster - delete.
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: cs3219g27
          APPLICATION_CREDENTIALS: ${{ secrets.GKE_SA_KEY }}
          CLUSTER_NAME: cs3219g27
          ZONE_NAME: asia-southeast1-a
        with:
          args: rollout restart -f gke/frontend-deployment.yaml
