name: frontend-cd

on:
  push:
    branches:
      - "main"
    paths:
      - frontend/**
  pull_request:
    branches: [main]
    paths:
      - frontend/**

jobs:
  Deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: npm install
      - run: REACT_APP_ENV=PROD npm run build 
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }} 
      - id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: 'frontend/build'
          destination: ${{ secrets.GCP_FRONTEND_BUCKET }}
          parent: false
