name: gateway-cd

on:
  push:
    branches:
      - "main"
    paths:
      - gke/gateway-deployment.yaml

jobs:
  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: kubectl - Google Cloud GKE cluster
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: cs3219g27
          APPLICATION_CREDENTIALS: ${{ secrets.GKE_SA_KEY }}
          CLUSTER_NAME: cs3219g27
          ZONE_NAME: asia-southeast1-a
        with:
          args: rollout restart -f gke/gateway-deployment.yaml
