name: user-service-ci

on:
  push:
    branches: [main]
    paths:
      - user-service/**
  pull_request:
    branches: [main]
    paths:
      - user-service/**

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./user-service

    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x, 15.x, 16.x]
        mongodb-version: ["4.2", "4.4", "5.0"]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: create env file
        run: |
          touch .env
          echo ENV=${{ secrets.USER_SERVICE_ENV }} >> .env
          echo DB_LOCAL_URI=${{ secrets.USER_SERVICE_DB_LOCAL_URI }} >> .env
          echo DB_CLOUD_URI=${{ secrets.USER_SERVICE_DB_CLOUD_URI }} >> .env
      - run: npm ci --no-optional
      - run: npm run build --if-present
      - run: npm test
